# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run vscode:package
  displayName: 'npm run vscode:package'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      dist/**
      docs/**
      **/*.vsix
      **/*.nupkg
      CHANGELOG.md
      LICENSE
      package.json
      README.md
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'extension'
    publishLocation: 'Container'

- task: gitmirror@0
  inputs:
    GitRepoUrl: 'https://8f35bc2410f3a67f3b3576293ee0766994e237f3@github.com/cloudsmithconsulting/cds-for-code.git'